backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"

    files:
      - name: "hero"
        label: "Hero"
        file: "public/content/hero.json"

        fields:
          - label: "Nombre"
            name: "name"
            widget: "string"

          - label: "Subtítulo"
            name: "subtitle"
            widget: "object"
            fields:
              - label: "English"
                name: "en"
                widget: "string"

              - label: "Español"
                name: "es"
                widget: "string"

          - label: "Frase"
            name: "quote"
            widget: "object"
            fields:
              - label: "English"
                name: "en"
                widget: "string"

              - label: "Español"
                name: "es"
                widget: "string"
