backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "test"
    label: "Test"
    files:
      - label: "Información"
        name: "info"
        file: "content/info.json"
        fields:
          - label: "Título"
            name: "title"
            widget: "string"